### ISSUE TITLE
Modal don't close with keyboard navigation

### ISSUE THREAD

**Issue by brunopulis** [pedrolaxe/modalcss#3]
Another issue i found was when the modal is open you cannot close it via keyboard. To fix this a little javascript required.

**Comment by pedrolaxe** [comment]
Boa Tarde @brunopulis 
Como a proposta do Modal é em CSS puro não adicionei algumas funções, mas posso criar um js adicional para funcionar este recurso.

**Comment by brunopulis** [comment]
@pedrolaxe Massa cara! :D seria bastante interessante, porque assim o modal iria ficar 100% acessível

**Comment by pedrolaxe** [comment]
@brunopulis irei trabalhar nisso assim que possível!

**Comment by pedrolaxe** [comment]
@brunopulis Caso resolvido! :)
Adicionei as novas funções na versão 1.0.4
Obrigado.
