### ISSUE TITLE
margin question 

### ISSUE THREAD

**Issue by xavierve** [pedrolaxe/modalcss#5]
Oi Pedro, Very nice trick , thanks !
I am trying to understand your code
`top: -50% and 50%` 
  seams to be for transition effects, ok
but 
`left: 50%; +  margin: -250px 0 0 -32%;`
and for small screens with
`left: 50%; +  margin: -250px 0 0 -18.2%`
are not clear for me.
Why adding such left positioning and negative margin?
why negative pixels for top?

I would like not only using it but also to learn from your excellent work
TIA

**Comment by pedrolaxe** [comment]
Hi :smiley: 
The negative margin because I used some resolutions presenting problems responsive.
